WavefrontError: have the fit function return only the coefficients
So that it could be called externally provided a vector of fitting
polynomials without returning one of its arguments.